[versions]
agp = "4.2.2"
androidxEspressoCore = "3.6.1"
androidxJunit = "1.1.3"
androidxJunitVersion = "1.2.1"
espressoCoreVersion = "3.4.0"
firebaseBom = "33.7.0"
hamcrestLibrary = "2.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
mockitoCore = "5.6.0"
recyclerview = "1.3.2"
rules = "1.6.1"
rulesVersion = "1.5.0"
firebaseFirestore = "25.1.1"
glance = "1.1.1"

[libraries]
core = { module = "androidx.test:core", version.ref = "rulesVersion" }
espresso-core-v340 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspressoCore" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrestLibrary" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v113 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
json = "org.json:json:20220924"
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
rules-v150 = { module = "androidx.test:rules", version.ref = "rulesVersion" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
glance = { group = "androidx.glance", name = "glance", version.ref = "glance" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
